#!/bin/sh
#--------------+
# START SCRIPT |
#--------------+
#
# Customize the following variables:
# QIAO_HOME: full path of application's installation directory
export QIAO_HOME=$PWD
# JAVA_HOME: Java7 home directory
export JAVA_HOME=/usr/java/jdk1.7.0_45
# MEMSIZE: application's java max virtual memory size
VMSIZE=1G
PERSIZE=128M
# JMX port number
JMXPORT=9982


# ---------------------------------------------------------------------

LIB=$QIAO_HOME/lib
CLASSPATH=$QIAO_HOME/conf
for f in $LIB/*.jar; do
  if [ -f $f ]; then
    CLASSPATH=${CLASSPATH}:$f
  fi
done

export CLASSPATH
MAIN_CLASS=com.aol.advertising.qiao.bootstrap.Bootstrap
PID_FILE=qiao.PID
QIAO_CFG=$QIAO_HOME/conf

JAVA_OPTS="-Xmx$VMSIZE -Xms$VMSIZE -XX:PermSize=$PERSIZE -XX:MaxPermSize=128M -XX:+UseParallelGC -XX:+UseParallelOldGC -XX:MaxGCPauseMillis=20 -XX:GCTimeRatio=99 -Djava.net.preferIPv4Stack=true"

JAVA_OPTS="-Dqiao.config.dir=$QIAO_CFG -Dqiao.home=$QIAO_HOME -Dnet.spy.log.LoggerImpl=net.spy.memcached.compat.log.Log4JLogger $JAVA_OPTS"
JAVA_OPTS="$JAVA_OPTS -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=$JMXPORT -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false"

$JAVA_HOME/bin/java $JAVA_OPTS -cp $CLASSPATH $MAIN_CLASS 2>&1>> $QIAO_HOME/logs/qiao.out &
echo $! > $PID_FILE
cat $PID_FILE
